version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
  - package-ecosystem: cargo
    directory: "/rust"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
