header:
  - path: "rust/src"
    license:
      spdx-id: Apache-2.0

  - path: "rust/src/python"
    license:
      spdx-id: LGPL-2.1-or-later

  - path: "tests"
    license:
      spdx-id: LGPL-2.1-or-later

  paths-ignore:
    - 'rust/target'
    - 'licenses'
    - '**/*.md'
    - '**/*.toml'
    - '**/*.yml'
    - 'LICENSE'
    - 'NOTICE'