---
specfile_path: nmstate.spec
upstream_package_name: nmstate
upstream_project_url: http://nmstate.io
srpm_build_deps:
  - git
actions:
  post-upstream-clone:
    - "bash -c 'rpm2cpio `./packaging/make_srpm.sh`|cpio -idmv'"
  create-archive:
    - "bash -c 'echo nmstate-$(cat VERSION).tar.gz'"
  get-current-version:
    - "cat VERSION"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - centos-stream-8-x86_64
        - centos-stream-9-x86_64
        - epel-8-x86_64
