---
specfile_path: nmstate.spec
upstream_package_name: nmstate
upstream_project_url: https://nmstate.io
enable_net: true
srpm_build_deps:
  - cargo
  - make
  - git
  - tar
  - xz
notifications:
  pull_request:
    successful_build: true
actions:
  post-upstream-clone:
    - "make packaging/nmstate.spec"
    - "cp packaging/nmstate.spec nmstate.spec"
  fix-spec-file:
    - "make dist"
  get-current-version:
    - "cat VERSION"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - centos-stream-9-x86_64
        - epel-9-x86_64
