---
specfile_path: nmstate.spec
upstream_package_name: nmstate
upstream_project_url: http://nmstate.io
enable_net: true
srpm_build_deps:
  - python3-pip
  - python3-setuptools_scm
actions:
  post-upstream-clone: "bash -c './packaging/make_spec.sh > nmstate.spec'"
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo nmstate-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - epel-8-x86_64
