---
specfile_path: nmstate.spec
upstream_package_name: nmstate
upstream_project_url: http://nmstate.io
srpm_build_deps:
  - make
  - git
actions:
  post-upstream-clone:
    - "make packaging/nmstate.spec"
    - "mv packaging/nmstate.spec ./"
  create-archive:
    - "env SKIP_VENDOR_CREATION=1 make dist"
  get-current-version:
    - "cat VERSION"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - centos-stream-8-x86_64
        - centos-stream-9-x86_64
        - epel-8-x86_64
        - epel-9-x86_64
