repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: make fmt_check
        language: system
        files: ^rust/.*\.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: make clippy_check
        language: system
        files: ^rust/.*\.rs$
        pass_filenames: false

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
