[package]
name = "nmstate-clib"
description = "Nmstate C binding"
version = "2.2.62"
authors = ["Gris Ge <fge@redhat.com>"]
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
name = "nmstate"
path = "lib.rs"
crate-type = ["cdylib", "staticlib"]
doc = false

[dependencies]
nmstate = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[features]
default = ["query_apply", "gen_conf"]
query_apply = ["nmstate/query_apply"]
gen_conf = ["nmstate/gen_conf"]
