// SPDX-License-Identifier: Apache-2.0

use std::{collections::HashSet, fmt::Write};

use tokio::io::{AsyncReadExt, AsyncWriteExt};

use crate::{
    BaseInterface, ErrorKind, InterfaceIdentifier, InterfaceState,
    InterfaceType, MergedInterfaces, NmstateError,
};

/// Comment added into our generated link files
const PERSIST_GENERATED_BY: &str = "# Generated by nmstate";
const SYSTEMD_LINK_FILE_PREFIX: &str = "98-nmstate-";

const SYSTEMD_NETWORK_LINK_FOLDER: &str = "/etc/systemd/network";

fn gen_nispor_iface_conf_for_alt_name(
    base_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> Result<Option<nispor::IfaceConf>, NmstateError> {
    let des_alt_names = if base_iface.state == InterfaceState::Absent {
        // For absent interfaces, remove current alt-names
        cur_iface.as_ref().and_then(|i| i.alt_names.as_ref())
    } else {
        base_iface.alt_names.as_ref()
    };

    if let Some(des_alt_names) = des_alt_names {
        let mut np_iface = nispor::IfaceConf::default();

        np_iface.state = match base_iface.state {
            InterfaceState::Up => nispor::IfaceState::Up,
            InterfaceState::Down => nispor::IfaceState::Down,
            // Other function will delete this interface, for purging
            InterfaceState::Absent => nispor::IfaceState::Down,
            _ => return Ok(None),
        };

        np_iface.name = base_iface.name.to_string();
        let cur_alt_names: HashSet<&str> = cur_iface
            .and_then(|i| i.alt_names.as_ref())
            .map(|v| v.as_slice())
            .unwrap_or(&[])
            .iter()
            .map(|entry| entry.name.as_str())
            .collect();
        let mut np_alt_names = Vec::new();
        for des_alt_name in des_alt_names {
            let des_alt_name_is_absent = des_alt_name.is_absent()
                || base_iface.state == InterfaceState::Absent;
            match (
                des_alt_name_is_absent,
                cur_alt_names.contains(&des_alt_name.name.as_str()),
            ) {
                (true, true) | (false, false) => {
                    np_alt_names.push(nispor::AltNameConf::new(
                        des_alt_name.name.to_string(),
                        des_alt_name_is_absent,
                    ));
                }
                (false, true) | (true, false) => {
                    // Already exist or already deleted, do nothing
                }
            }
        }
        if !np_alt_names.is_empty() {
            np_iface.alt_names = np_alt_names;
        }
        Ok(Some(np_iface))
    } else {
        Ok(None)
    }
}

pub(crate) async fn apply_ifaces_alt_names(
    merged_ifaces: &MergedInterfaces,
) -> Result<(), NmstateError> {
    let mut np_ifaces: Vec<nispor::IfaceConf> = Vec::new();

    for merged_iface in merged_ifaces.kernel_ifaces.values() {
        let apply_iface = if let Some(i) = merged_iface.for_apply.as_ref() {
            i
        } else {
            continue;
        };
        // A virtual interface being deleted takes its alt-names with it, so
        // skip the nispor removal, which would otherwise race the deletion.
        if apply_iface.base_iface().state == InterfaceState::Absent
            && apply_iface.is_virtual()
        {
            continue;
        }
        let cur_iface = merged_iface.current.as_ref().map(|i| i.base_iface());
        if let Some(np_iface) = gen_nispor_iface_conf_for_alt_name(
            apply_iface.base_iface(),
            cur_iface,
        )? {
            np_ifaces.push(np_iface);
        }
    }

    if !np_ifaces.is_empty() {
        let mut net_conf = nispor::NetConf::default();
        net_conf.ifaces = Some(np_ifaces);

        if let Err(e) = net_conf.apply_async().await {
            return Err(NmstateError::new(
                ErrorKind::PluginFailure,
                format!("Failed to change alt-name: {} {}", e.kind, e.msg),
            ));
        }
    }
    Ok(())
}

pub(crate) async fn persist_alt_name_config(
    merged_ifaces: &MergedInterfaces,
) -> Result<(), NmstateError> {
    for merged_iface in merged_ifaces.kernel_ifaces.values() {
        let apply_iface = if let Some(i) = merged_iface.for_apply.as_ref() {
            i.base_iface()
        } else {
            continue;
        };
        if apply_iface.state == InterfaceState::Absent {
            remove_systemd_network_link_file(apply_iface.name.as_str()).await?
        } else if let Some(alt_names) = apply_iface.alt_names.as_ref() {
            let mut saved_alt_names =
                load_saved_alt_names(apply_iface.name.as_str()).await;
            for alt_name in alt_names {
                if alt_name.is_absent() {
                    saved_alt_names.remove(&alt_name.name);
                } else {
                    saved_alt_names.insert(alt_name.name.to_string());
                }
            }
            if saved_alt_names.is_empty() {
                remove_systemd_network_link_file(apply_iface.name.as_str())
                    .await?
            } else {
                save_systemd_network_link_file(
                    apply_iface,
                    merged_iface.current.as_ref().map(|i| i.base_iface()),
                    &saved_alt_names,
                )
                .await?;
            }
        }
    }
    Ok(())
}

// The systemd udev does not merge along all link files, the matched link
// file with smallest number will be solely used.
// So we use 98-nmstate-<iface_name>link which holds precedence than systemd
// fallback file 99-default.link.
fn gen_systemd_link_file_path(iface_name: &str) -> std::path::PathBuf {
    format!(
        "{SYSTEMD_NETWORK_LINK_FOLDER}/{SYSTEMD_LINK_FILE_PREFIX}{iface_name}.\
         link"
    )
    .into()
}

async fn load_saved_alt_names(iface_name: &str) -> HashSet<String> {
    let mut ret: HashSet<String> = HashSet::new();
    let file_path = gen_systemd_link_file_path(iface_name);

    let mut fd = match tokio::fs::File::open(&file_path).await {
        Ok(fd) => fd,
        Err(e) => {
            log::debug!("Failed to open {}: {e}", file_path.display());
            return ret;
        }
    };

    let mut content = String::new();
    if let Err(e) = fd.read_to_string(&mut content).await {
        log::debug!("Failed to read {}: {e}", file_path.display());
        return ret;
    }

    for line in content.lines() {
        if let Some(alt_name) = line.strip_prefix("AlternativeName=") {
            ret.insert(alt_name.trim().to_string());
        }
    }

    ret
}

async fn remove_systemd_network_link_file(
    iface_name: &str,
) -> Result<(), NmstateError> {
    let file_path = gen_systemd_link_file_path(iface_name);
    if file_path.exists() {
        log::debug!("Deleting {}", file_path.display());
        tokio::fs::remove_file(&file_path).await.map_err(|e| {
            NmstateError::new(
                ErrorKind::PluginFailure,
                format!("Failed to delete file {}: {e}", file_path.display()),
            )
        })
    } else {
        Ok(())
    }
}

fn gen_systemd_match_rules(
    des_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> Result<String, NmstateError> {
    let (identifier, src_iface) = effective_identifier(des_iface, cur_iface);

    match identifier {
        InterfaceIdentifier::MacAddress => {
            // Include driver in case two NICs hold the same MAC.
            // (e.g. Microsoft Azure Network Adapter)
            let driver = cur_iface.and_then(|i| i.driver.as_ref());
            mac_match_rules(
                src_iface.permanent_mac_address.as_ref(),
                src_iface.mac_address.as_ref(),
                driver,
            )
            .ok_or_else(|| {
                NmstateError::new(
                    ErrorKind::Bug,
                    format!(
                        "Got no MAC address for `identifier:mac-address` on \
                         interface {}, should be failed by previous checker",
                        des_iface.name
                    ),
                )
            })
        }
        InterfaceIdentifier::PciAddress => {
            if let Some(pci_addr) = src_iface.pci_address.as_ref() {
                Ok(format!("Path=pci-{pci_addr}"))
            } else {
                Err(NmstateError::new(
                    ErrorKind::Bug,
                    format!(
                        "Got no PCI address for `identifier:pci-address` on \
                         interface {}, should be failed by previous checker",
                        des_iface.name
                    ),
                ))
            }
        }
        InterfaceIdentifier::Name => {
            Ok(gen_systemd_name_match_rules(des_iface, cur_iface))
        }
    }
}

// Pick the identifier and the interface holding its value. An explicit desired
// identifier wins; a live mac/pci identifier is inherited only when the iface
// owns it (permanent MAC or PCI), never a stacked iface's borrowed MAC, since
// the persisted `.link` file outlives the port set that MAC came from.
fn effective_identifier<'a>(
    des_iface: &'a BaseInterface,
    cur_iface: Option<&'a BaseInterface>,
) -> (InterfaceIdentifier, &'a BaseInterface) {
    if let Some(id) = des_iface.identifier {
        return (id, des_iface);
    }
    if let Some(cur) = cur_iface {
        match cur.identifier {
            Some(InterfaceIdentifier::MacAddress)
                if cur.permanent_mac_address.is_some() =>
            {
                return (InterfaceIdentifier::MacAddress, cur);
            }
            Some(InterfaceIdentifier::PciAddress)
                if cur.pci_address.is_some() =>
            {
                return (InterfaceIdentifier::PciAddress, cur);
            }
            _ => {}
        }
    }
    (InterfaceIdentifier::Name, des_iface)
}

// Fallback for the `name` identifier: match the most stable attribute the live
// interface owns (permanent MAC, then PCI, with driver to disambiguate NICs
// sharing a MAC). A borrowed MAC is never used, so software interfaces fall
// through to `OriginalName`; ethernet also accepts its own current MAC first.
fn gen_systemd_name_match_rules(
    des_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> String {
    if des_iface.iface_type != InterfaceType::Ethernet {
        return cur_iface.and_then(owned_hw_match_rules).unwrap_or_else(|| {
            let name = cur_iface
                .map(|i| i.name.as_str())
                .unwrap_or(des_iface.name.as_str());
            format!("OriginalName={name}")
        });
    }

    if let Some(cur_iface) = cur_iface {
        owned_hw_match_rules(cur_iface)
            .or_else(|| {
                mac_match_rules(
                    None,
                    cur_iface.mac_address.as_ref(),
                    cur_iface.driver.as_ref(),
                )
            })
            .unwrap_or_else(|| format!("OriginalName={}", cur_iface.name))
    } else {
        // User is creating the ethernet interface or gen_conf mode
        mac_match_rules(
            None,
            des_iface.mac_address.as_ref(),
            des_iface.driver.as_ref(),
        )
        .unwrap_or_else(|| format!("OriginalName={}", des_iface.name))
    }
}

// A stable hardware identifier the interface owns: permanent MAC (with driver)
// or PCI path. None for a borrowed MAC (e.g. a VLAN), which matches by name.
fn owned_hw_match_rules(cur_iface: &BaseInterface) -> Option<String> {
    mac_match_rules(
        cur_iface.permanent_mac_address.as_ref(),
        None,
        cur_iface.driver.as_ref(),
    )
    .or_else(|| {
        cur_iface
            .pci_address
            .as_ref()
            .map(|pci_addr| format!("Path=pci-{pci_addr}"))
    })
}

fn mac_match_rules(
    permanent_mac: Option<&String>,
    mac: Option<&String>,
    driver: Option<&String>,
) -> Option<String> {
    let mut rules = if let Some(mac) = permanent_mac {
        format!("PermanentMACAddress={mac}")
    } else {
        let mac = mac?;
        format!("MACAddress={mac}")
    };
    if let Some(driver) = driver {
        write!(rules, "\nDriver={driver}").ok();
    }
    Some(rules)
}

async fn save_systemd_network_link_file(
    des_base_iface: &BaseInterface,
    cur_base_iface: Option<&BaseInterface>,
    alt_names: &HashSet<String>,
) -> Result<(), NmstateError> {
    if !std::path::Path::new(SYSTEMD_NETWORK_LINK_FOLDER).exists() {
        tokio::fs::create_dir_all(SYSTEMD_NETWORK_LINK_FOLDER)
            .await
            .map_err(|e| {
                NmstateError::new(
                    ErrorKind::PluginFailure,
                    format!(
                        "Failed to create folder \
                         {SYSTEMD_NETWORK_LINK_FOLDER}: {e}"
                    ),
                )
            })?;
    }
    let iface_name = des_base_iface.name.as_str();

    let match_rules = gen_systemd_match_rules(des_base_iface, cur_base_iface)?;

    let file_path = gen_systemd_link_file_path(iface_name);
    let mut content = {
        #[cfg_attr(any(), rustfmt::skip)]
        format!(
            "{PERSIST_GENERATED_BY}\n\
            [Match]\n\
            {match_rules}\n\n\
            [Link]\n"
        )
    };
    let alt_names: Vec<&str> = alt_names.iter().map(|s| s.as_str()).collect();
    for alt_name in alt_names.iter() {
        writeln!(content, "AlternativeName={alt_name}").ok();
    }
    // Since systemd stop using other naming policy after matched our link file
    // we should explicitly name this interface to current interface name,
    // otherwise, reboot will get NIC named as eth0.
    writeln!(content, "Name={iface_name}").ok();

    log::info!(
        "Creating {} for alt-names of interface {iface_name}",
        file_path.display(),
    );
    log::debug!(
        "Creating file {} with content: {}",
        file_path.display(),
        content
    );

    let mut fd = tokio::fs::File::create(&file_path).await.map_err(|e| {
        NmstateError::new(
            ErrorKind::PluginFailure,
            format!("Failed to create file {}: {e}", file_path.display()),
        )
    })?;
    fd.write_all(content.as_bytes()).await.map_err(|e| {
        NmstateError::new(
            ErrorKind::PluginFailure,
            format!("Failed to write file {}: {e}", file_path.display()),
        )
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Desired VLAN has no MAC; the live one carries the inherited bond MAC.
    #[test]
    fn vlan_reapply_uses_original_name() {
        let mut des = BaseInterface::new();
        des.name = "external0".to_string();
        des.iface_type = InterfaceType::Vlan;

        let mut cur = des.clone();
        cur.mac_address = Some("52:54:00:80:77:C9".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "OriginalName=external0");
    }

    // The name fallback keys on the live kernel name, not the desired name, so
    // udev matches the interface it names.
    #[test]
    fn non_eth_original_name_uses_current_name() {
        let mut des = BaseInterface::new();
        des.name = "bond-vlan".to_string();
        des.iface_type = InterfaceType::Vlan;

        let mut cur = des.clone();
        cur.name = "external0".to_string();

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "OriginalName=external0");
    }

    // Create path (no current iface), non-VLAN software type, MAC ignored.
    #[test]
    fn software_iface_create_uses_original_name() {
        let mut des = BaseInterface::new();
        des.name = "bond0".to_string();
        des.iface_type = InterfaceType::Bond;
        des.mac_address = Some("52:54:00:80:77:C9".to_string());

        let rules = gen_systemd_match_rules(&des, None).unwrap();
        assert_eq!(rules, "OriginalName=bond0");
    }

    #[test]
    fn ethernet_reapply_uses_permanent_mac() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "PermanentMACAddress=52:54:00:11:22:33");
    }

    // A physical non-ethernet iface (InfiniBand) owns a permanent MAC, so an
    // alt-names-only reapply pins to it instead of its renameable kernel name.
    #[test]
    fn infiniband_reapply_uses_permanent_mac() {
        let mut des = BaseInterface::new();
        des.name = "mlx0".to_string();
        des.iface_type = InterfaceType::InfiniBand;

        let mut cur = des.clone();
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "PermanentMACAddress=52:54:00:11:22:33");
    }

    // A physical non-ethernet iface owning a PCI address but no permanent MAC
    // pins to the PCI path rather than the kernel name.
    #[test]
    fn non_eth_reapply_uses_pci_path() {
        let mut des = BaseInterface::new();
        des.name = "mlx0".to_string();
        des.iface_type = InterfaceType::InfiniBand;

        let mut cur = des.clone();
        cur.pci_address =
            Some(crate::PciAddress::try_from("0000:00:1f.6").unwrap());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "Path=pci-0000:00:1f.6");
    }

    // A live mac-address identifier without a permanent MAC (borrowed from a
    // lower device) is not inherited.
    #[test]
    fn inherited_mac_ignored_for_virtual_iface() {
        let mut des = BaseInterface::new();
        des.name = "vlan0".to_string();
        des.iface_type = InterfaceType::Vlan;

        let mut cur = des.clone();
        cur.identifier = Some(InterfaceIdentifier::MacAddress);
        cur.mac_address = Some("52:54:00:80:77:C9".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "OriginalName=vlan0");
    }

    // A physical NIC with a live mac-address identifier owns a permanent MAC,
    // so an alt-names-only reapply inherits it and matches by permanent MAC.
    #[test]
    fn inherited_mac_uses_permanent_for_physical() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.identifier = Some(InterfaceIdentifier::MacAddress);
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "PermanentMACAddress=52:54:00:11:22:33");
    }

    // A live pci-address identifier is inherited over the name fallback's
    // default order, pinning the PCI path the user originally chose.
    #[test]
    fn inherited_pci_identifier_preserved() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.identifier = Some(InterfaceIdentifier::PciAddress);
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());
        cur.pci_address =
            Some(crate::PciAddress::try_from("0000:00:1f.6").unwrap());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "Path=pci-0000:00:1f.6");
    }

    // Explicit `identifier: name` wins over the live mac-address identifier.
    #[test]
    fn explicit_name_identifier_keeps_original_name() {
        let mut des = BaseInterface::new();
        des.name = "vlan0".to_string();
        des.iface_type = InterfaceType::Vlan;
        des.identifier = Some(InterfaceIdentifier::Name);

        let mut cur = des.clone();
        cur.identifier = Some(InterfaceIdentifier::MacAddress);
        cur.mac_address = Some("52:54:00:80:77:C9".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "OriginalName=vlan0");
    }

    // mac-address identifier appends the live driver to disambiguate two NICs
    // sharing one MAC.
    #[test]
    fn mac_identifier_appends_current_driver() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;
        des.identifier = Some(InterfaceIdentifier::MacAddress);
        des.mac_address = Some("52:54:00:11:22:33".to_string());

        let mut cur = des.clone();
        cur.driver = Some("e1000e".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "MACAddress=52:54:00:11:22:33\nDriver=e1000e");
    }

    #[test]
    fn pci_identifier_uses_path() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;
        des.identifier = Some(InterfaceIdentifier::PciAddress);
        des.pci_address =
            Some(crate::PciAddress::try_from("0000:00:1f.6").unwrap());

        let rules = gen_systemd_match_rules(&des, None).unwrap();
        assert_eq!(rules, "Path=pci-0000:00:1f.6");
    }

    #[test]
    fn mac_identifier_without_mac_is_bug() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;
        des.identifier = Some(InterfaceIdentifier::MacAddress);

        let e = gen_systemd_match_rules(&des, None).unwrap_err();
        assert_eq!(e.kind(), ErrorKind::Bug);
    }

    #[test]
    fn pci_identifier_without_pci_is_bug() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;
        des.identifier = Some(InterfaceIdentifier::PciAddress);

        let e = gen_systemd_match_rules(&des, None).unwrap_err();
        assert_eq!(e.kind(), ErrorKind::Bug);
    }

    #[test]
    fn name_fallback_uses_permanent_mac_and_driver() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());
        cur.driver = Some("e1000e".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(
            rules,
            "PermanentMACAddress=52:54:00:11:22:33\nDriver=e1000e"
        );
    }

    #[test]
    fn name_fallback_uses_current_mac_and_driver() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.mac_address = Some("52:54:00:11:22:33".to_string());
        cur.driver = Some("e1000e".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "MACAddress=52:54:00:11:22:33\nDriver=e1000e");
    }

    // Explicit desired mac-address identifier is honoured on a non-ethernet
    // iface too, matching by MAC rather than falling back to OriginalName.
    #[test]
    fn non_eth_explicit_mac_identifier_uses_mac() {
        let mut des = BaseInterface::new();
        des.name = "vlan0".to_string();
        des.iface_type = InterfaceType::Vlan;
        des.identifier = Some(InterfaceIdentifier::MacAddress);
        des.mac_address = Some("52:54:00:11:22:33".to_string());

        let rules = gen_systemd_match_rules(&des, None).unwrap();
        assert_eq!(rules, "MACAddress=52:54:00:11:22:33");
    }

    // Permanent MAC wins when both a permanent and a current MAC are present.
    #[test]
    fn permanent_mac_preferred_over_current() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let mut cur = des.clone();
        cur.permanent_mac_address = Some("52:54:00:11:22:33".to_string());
        cur.mac_address = Some("52:54:00:AA:BB:CC".to_string());

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "PermanentMACAddress=52:54:00:11:22:33");
    }

    // Ethernet reapply with no MAC, PCI, or permanent MAC on the live iface
    // falls back to its current kernel name.
    #[test]
    fn eth_name_fallback_with_no_attributes() {
        let mut des = BaseInterface::new();
        des.name = "eth0".to_string();
        des.iface_type = InterfaceType::Ethernet;

        let cur = des.clone();

        let rules = gen_systemd_match_rules(&des, Some(&cur)).unwrap();
        assert_eq!(rules, "OriginalName=eth0");
    }
}
