// SPDX-License-Identifier: Apache-2.0

use std::{collections::HashSet, fmt::Write};

use tokio::io::{AsyncReadExt, AsyncWriteExt};

use crate::{
    BaseInterface, ErrorKind, InterfaceIdentifier, InterfaceState,
    MergedInterfaces, NmstateError,
};

/// Comment added into our generated link files
const PERSIST_GENERATED_BY: &str = "# Generated by nmstate";
const SYSTEMD_LINK_FILE_PREFIX: &str = "98-nmstate-";

const SYSTEMD_NETWORK_LINK_FOLDER: &str = "/etc/systemd/network";

fn gen_nispor_iface_conf_for_alt_name(
    base_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> Result<Option<nispor::IfaceConf>, NmstateError> {
    let des_alt_names = if base_iface.state == InterfaceState::Absent {
        // For absent interfaces, remove current alt-names
        cur_iface.as_ref().and_then(|i| i.alt_names.as_ref())
    } else {
        base_iface.alt_names.as_ref()
    };

    if let Some(des_alt_names) = des_alt_names {
        let mut np_iface = nispor::IfaceConf::default();

        np_iface.state = match base_iface.state {
            InterfaceState::Up => nispor::IfaceState::Up,
            InterfaceState::Down => nispor::IfaceState::Down,
            // Other function will delete this interface, for purging
            InterfaceState::Absent => nispor::IfaceState::Down,
            _ => return Ok(None),
        };

        np_iface.name = base_iface.name.to_string();
        let cur_alt_names: HashSet<&str> = cur_iface
            .and_then(|i| i.alt_names.as_ref())
            .map(|v| v.as_slice())
            .unwrap_or(&[])
            .iter()
            .map(|entry| entry.name.as_str())
            .collect();
        let mut np_alt_names = Vec::new();
        for des_alt_name in des_alt_names {
            let des_alt_name_is_absent = des_alt_name.is_absent()
                || base_iface.state == InterfaceState::Absent;
            match (
                des_alt_name_is_absent,
                cur_alt_names.contains(&des_alt_name.name.as_str()),
            ) {
                (true, true) | (false, false) => {
                    np_alt_names.push(nispor::AltNameConf::new(
                        des_alt_name.name.to_string(),
                        des_alt_name_is_absent,
                    ));
                }
                (false, true) | (true, false) => {
                    // Already exist or already deleted, do nothing
                }
            }
        }
        if !np_alt_names.is_empty() {
            np_iface.alt_names = np_alt_names;
        }
        Ok(Some(np_iface))
    } else {
        Ok(None)
    }
}

pub(crate) async fn apply_ifaces_alt_names(
    merged_ifaces: &MergedInterfaces,
) -> Result<(), NmstateError> {
    let mut np_ifaces: Vec<nispor::IfaceConf> = Vec::new();

    for merged_iface in merged_ifaces.kernel_ifaces.values() {
        let apply_iface = if let Some(i) = merged_iface.for_apply.as_ref() {
            i.base_iface()
        } else {
            continue;
        };
        let cur_iface = merged_iface.current.as_ref().map(|i| i.base_iface());
        if let Some(np_iface) =
            gen_nispor_iface_conf_for_alt_name(apply_iface, cur_iface)?
        {
            np_ifaces.push(np_iface);
        }
    }

    if !np_ifaces.is_empty() {
        let mut net_conf = nispor::NetConf::default();
        net_conf.ifaces = Some(np_ifaces);

        if let Err(e) = net_conf.apply_async().await {
            return Err(NmstateError::new(
                ErrorKind::PluginFailure,
                format!("Failed to change alt-name: {} {}", e.kind, e.msg),
            ));
        }
    }
    Ok(())
}

pub(crate) async fn persist_alt_name_config(
    merged_ifaces: &MergedInterfaces,
) -> Result<(), NmstateError> {
    for merged_iface in merged_ifaces.kernel_ifaces.values() {
        let apply_iface = if let Some(i) = merged_iface.for_apply.as_ref() {
            i.base_iface()
        } else {
            continue;
        };
        if apply_iface.state == InterfaceState::Absent {
            remove_systemd_network_link_file(apply_iface.name.as_str()).await?
        } else if let Some(alt_names) = apply_iface.alt_names.as_ref() {
            let mut saved_alt_names =
                load_saved_alt_names(apply_iface.name.as_str()).await;
            for alt_name in alt_names {
                if alt_name.is_absent() {
                    saved_alt_names.remove(&alt_name.name);
                } else {
                    saved_alt_names.insert(alt_name.name.to_string());
                }
            }
            if saved_alt_names.is_empty() {
                remove_systemd_network_link_file(apply_iface.name.as_str())
                    .await?
            } else {
                save_systemd_network_link_file(
                    apply_iface,
                    merged_iface.current.as_ref().map(|i| i.base_iface()),
                    &saved_alt_names,
                )
                .await?;
            }
        }
    }
    Ok(())
}

// The systemd udev does not merge along all link files, the matched link
// file with smallest number will be solely used.
// So we use 98-nmstate-<iface_name>link which holds precedence than systemd
// fallback file 99-default.link.
fn gen_systemd_link_file_path(iface_name: &str) -> std::path::PathBuf {
    format!(
        "{SYSTEMD_NETWORK_LINK_FOLDER}/{SYSTEMD_LINK_FILE_PREFIX}{iface_name}.\
         link"
    )
    .into()
}

async fn load_saved_alt_names(iface_name: &str) -> HashSet<String> {
    let mut ret: HashSet<String> = HashSet::new();
    let file_path = gen_systemd_link_file_path(iface_name);

    let mut fd = match tokio::fs::File::open(&file_path).await {
        Ok(fd) => fd,
        Err(e) => {
            log::debug!("Failed to open {}: {e}", file_path.display());
            return ret;
        }
    };

    let mut content = String::new();
    if let Err(e) = fd.read_to_string(&mut content).await {
        log::debug!("Failed to read {}: {e}", file_path.display());
        return ret;
    }

    for line in content.lines() {
        if let Some(alt_name) = line.strip_prefix("AlternativeName=") {
            ret.insert(alt_name.trim().to_string());
        }
    }

    ret
}

async fn remove_systemd_network_link_file(
    iface_name: &str,
) -> Result<(), NmstateError> {
    let file_path = gen_systemd_link_file_path(iface_name);
    if file_path.exists() {
        log::debug!("Deleting {}", file_path.display());
        tokio::fs::remove_file(&file_path).await.map_err(|e| {
            NmstateError::new(
                ErrorKind::PluginFailure,
                format!("Failed to delete file {}: {e}", file_path.display()),
            )
        })
    } else {
        Ok(())
    }
}

fn gen_systemd_match_rules(
    des_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> Result<String, NmstateError> {
    let (identifier, src_iface) = effective_identifier(des_iface, cur_iface);

    match identifier {
        InterfaceIdentifier::MacAddress => {
            // Include driver in case two NICs hold the same MAC.
            // (e.g. Microsoft Azure Network Adapter)
            let driver = cur_iface.and_then(|i| i.driver.as_ref());
            mac_match_rules(
                src_iface.permanent_mac_address.as_ref(),
                src_iface.mac_address.as_ref(),
                driver,
            )
            .ok_or_else(|| {
                NmstateError::new(
                    ErrorKind::Bug,
                    format!(
                        "Got no MAC address for `identifier:mac-address` on \
                         interface {}, should be failed by previous checker",
                        des_iface.name
                    ),
                )
            })
        }
        InterfaceIdentifier::PciAddress => {
            if let Some(pci_addr) = src_iface.pci_address.as_ref() {
                Ok(format!("Path=pci-{pci_addr}"))
            } else {
                Err(NmstateError::new(
                    ErrorKind::Bug,
                    format!(
                        "Got no PCI address for `identifier:pci-address` on \
                         interface {}, should be failed by previous checker",
                        des_iface.name
                    ),
                ))
            }
        }
        InterfaceIdentifier::Name => {
            Ok(gen_systemd_name_match_rules(des_iface, cur_iface))
        }
    }
}

// Resolve the identifier to match on and the interface that supplies its
// MAC/PCI value. Desired state's explicit identifier is honoured as-is; when it
// is absent the current interface's identifier is inherited.
fn effective_identifier<'a>(
    des_iface: &'a BaseInterface,
    cur_iface: Option<&'a BaseInterface>,
) -> (InterfaceIdentifier, &'a BaseInterface) {
    if let Some(id) = des_iface.identifier {
        return (id, des_iface);
    }
    if let Some(cur) = cur_iface {
        match cur.identifier {
            Some(InterfaceIdentifier::MacAddress) => {
                return (InterfaceIdentifier::MacAddress, cur);
            }
            Some(InterfaceIdentifier::PciAddress) => {
                return (InterfaceIdentifier::PciAddress, cur);
            }
            _ => {}
        }
    }
    (InterfaceIdentifier::Name, des_iface)
}

// Fallback used when the resolved identifier is `name` (the default).
//
// The kernel name is unpredictable, so match on the most stable attribute
// available: permanent MAC, then PCI path, then current MAC, each with driver
// when known to disambiguate NICs sharing a MAC (e.g. Azure's Microsoft Azure
// Network Adapter).
fn gen_systemd_name_match_rules(
    des_iface: &BaseInterface,
    cur_iface: Option<&BaseInterface>,
) -> String {
    if let Some(cur_iface) = cur_iface {
        if let Some(rules) = mac_match_rules(
            cur_iface.permanent_mac_address.as_ref(),
            None,
            cur_iface.driver.as_ref(),
        ) {
            rules
        } else if let Some(pci_addr) = cur_iface.pci_address.as_ref() {
            format!("Path=pci-{pci_addr}")
        } else if let Some(rules) = mac_match_rules(
            None,
            cur_iface.mac_address.as_ref(),
            cur_iface.driver.as_ref(),
        ) {
            rules
        } else {
            format!("OriginalName={}", cur_iface.name)
        }
    } else {
        // User is creating the ethernet interface or gen_conf mode
        mac_match_rules(
            None,
            des_iface.mac_address.as_ref(),
            des_iface.driver.as_ref(),
        )
        .unwrap_or_else(|| format!("OriginalName={}", des_iface.name))
    }
}

fn mac_match_rules(
    permanent_mac: Option<&String>,
    mac: Option<&String>,
    driver: Option<&String>,
) -> Option<String> {
    let mut rules = if let Some(mac) = permanent_mac {
        format!("PermanentMACAddress={mac}")
    } else {
        let mac = mac?;
        format!("MACAddress={mac}")
    };
    if let Some(driver) = driver {
        write!(rules, "\nDriver={driver}").ok();
    }
    Some(rules)
}

async fn save_systemd_network_link_file(
    des_base_iface: &BaseInterface,
    cur_base_iface: Option<&BaseInterface>,
    alt_names: &HashSet<String>,
) -> Result<(), NmstateError> {
    if !std::path::Path::new(SYSTEMD_NETWORK_LINK_FOLDER).exists() {
        tokio::fs::create_dir_all(SYSTEMD_NETWORK_LINK_FOLDER)
            .await
            .map_err(|e| {
                NmstateError::new(
                    ErrorKind::PluginFailure,
                    format!(
                        "Failed to create folder \
                         {SYSTEMD_NETWORK_LINK_FOLDER}: {e}"
                    ),
                )
            })?;
    }
    let iface_name = des_base_iface.name.as_str();

    let match_rules = gen_systemd_match_rules(des_base_iface, cur_base_iface)?;

    let file_path = gen_systemd_link_file_path(iface_name);
    let mut content = {
        #[cfg_attr(any(), rustfmt::skip)]
        format!(
            "{PERSIST_GENERATED_BY}\n\
            [Match]\n\
            {match_rules}\n\n\
            [Link]\n"
        )
    };
    let alt_names: Vec<&str> = alt_names.iter().map(|s| s.as_str()).collect();
    for alt_name in alt_names.iter() {
        writeln!(content, "AlternativeName={alt_name}").ok();
    }
    // Since systemd stop using other naming policy after matched our link file
    // we should explicitly name this interface to current interface name,
    // otherwise, reboot will get NIC named as eth0.
    writeln!(content, "Name={iface_name}").ok();

    log::info!(
        "Creating {} for alt-names of interface {iface_name}",
        file_path.display(),
    );
    log::debug!(
        "Creating file {} with content: {}",
        file_path.display(),
        content
    );

    let mut fd = tokio::fs::File::create(&file_path).await.map_err(|e| {
        NmstateError::new(
            ErrorKind::PluginFailure,
            format!("Failed to create file {}: {e}", file_path.display()),
        )
    })?;
    fd.write_all(content.as_bytes()).await.map_err(|e| {
        NmstateError::new(
            ErrorKind::PluginFailure,
            format!("Failed to write file {}: {e}", file_path.display()),
        )
    })?;
    Ok(())
}
