//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The NMState Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseInterface) DeepCopyInto(out *BaseInterface) {
	*out = *in
	if in.ProfileName != nil {
		in, out := &in.ProfileName, &out.ProfileName
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
	if in.Mtu != nil {
		in, out := &in.Mtu, &out.Mtu
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MinMtu != nil {
		in, out := &in.MinMtu, &out.MinMtu
		*out = new(uint64)
		**out = **in
	}
	if in.MaxMtu != nil {
		in, out := &in.MaxMtu, &out.MaxMtu
		*out = new(uint64)
		**out = **in
	}
	if in.WaitIp != nil {
		in, out := &in.WaitIp, &out.WaitIp
		*out = new(WaitIp)
		**out = **in
	}
	if in.Ipv4 != nil {
		in, out := &in.Ipv4, &out.Ipv4
		*out = new(InterfaceIp)
		(*in).DeepCopyInto(*out)
	}
	if in.Ipv6 != nil {
		in, out := &in.Ipv6, &out.Ipv6
		*out = new(InterfaceIp)
		(*in).DeepCopyInto(*out)
	}
	if in.Mptcp != nil {
		in, out := &in.Mptcp, &out.Mptcp
		*out = new(MptcpConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(string)
		**out = **in
	}
	if in.AcceptAllMacAddresses != nil {
		in, out := &in.AcceptAllMacAddresses, &out.AcceptAllMacAddresses
		*out = new(bool)
		**out = **in
	}
	if in.CopyMacFrom != nil {
		in, out := &in.CopyMacFrom, &out.CopyMacFrom
		*out = new(string)
		**out = **in
	}
	if in.Ovsdb != nil {
		in, out := &in.Ovsdb, &out.Ovsdb
		*out = new(OvsDbIfaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ieee8021X != nil {
		in, out := &in.Ieee8021X, &out.Ieee8021X
		*out = new(Ieee8021XConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Lldp != nil {
		in, out := &in.Lldp, &out.Lldp
		*out = new(LldpConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ethtool != nil {
		in, out := &in.Ethtool, &out.Ethtool
		*out = new(EthtoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Dispatch != nil {
		in, out := &in.Dispatch, &out.Dispatch
		*out = new(DispatchConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseInterface.
func (in *BaseInterface) DeepCopy() *BaseInterface {
	if in == nil {
		return nil
	}
	out := new(BaseInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BondConfig) DeepCopyInto(out *BondConfig) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(BondMode)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(BondOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.PortsConfig != nil {
		in, out := &in.PortsConfig, &out.PortsConfig
		*out = new([]BondPortConfig)
		if **in != nil {
			in, out := *in, *out
			*out = make([]BondPortConfig, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondConfig.
func (in *BondConfig) DeepCopy() *BondConfig {
	if in == nil {
		return nil
	}
	out := new(BondConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BondInterface) DeepCopyInto(out *BondInterface) {
	*out = *in
	if in.Bond != nil {
		in, out := &in.Bond, &out.Bond
		*out = new(BondConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondInterface.
func (in *BondInterface) DeepCopy() *BondInterface {
	if in == nil {
		return nil
	}
	out := new(BondInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BondOptions) DeepCopyInto(out *BondOptions) {
	*out = *in
	if in.AdActorSysPrio != nil {
		in, out := &in.AdActorSysPrio, &out.AdActorSysPrio
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.AdActorSystem != nil {
		in, out := &in.AdActorSystem, &out.AdActorSystem
		*out = new(string)
		**out = **in
	}
	if in.AdSelect != nil {
		in, out := &in.AdSelect, &out.AdSelect
		*out = new(BondAdSelect)
		**out = **in
	}
	if in.AdUserPortKey != nil {
		in, out := &in.AdUserPortKey, &out.AdUserPortKey
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.AllSlavesActive != nil {
		in, out := &in.AllSlavesActive, &out.AllSlavesActive
		*out = new(BondAllPortsActive)
		**out = **in
	}
	if in.ArpAllTargets != nil {
		in, out := &in.ArpAllTargets, &out.ArpAllTargets
		*out = new(BondArpAllTargets)
		**out = **in
	}
	if in.ArpInterval != nil {
		in, out := &in.ArpInterval, &out.ArpInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.ArpIpTarget != nil {
		in, out := &in.ArpIpTarget, &out.ArpIpTarget
		*out = new(string)
		**out = **in
	}
	if in.ArpValidate != nil {
		in, out := &in.ArpValidate, &out.ArpValidate
		*out = new(BondArpValidate)
		**out = **in
	}
	if in.Downdelay != nil {
		in, out := &in.Downdelay, &out.Downdelay
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.FailOverMac != nil {
		in, out := &in.FailOverMac, &out.FailOverMac
		*out = new(BondFailOverMac)
		**out = **in
	}
	if in.LacpRate != nil {
		in, out := &in.LacpRate, &out.LacpRate
		*out = new(BondLacpRate)
		**out = **in
	}
	if in.LpInterval != nil {
		in, out := &in.LpInterval, &out.LpInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Miimon != nil {
		in, out := &in.Miimon, &out.Miimon
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MinLinks != nil {
		in, out := &in.MinLinks, &out.MinLinks
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.NumGratArp != nil {
		in, out := &in.NumGratArp, &out.NumGratArp
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.NumUnsolNa != nil {
		in, out := &in.NumUnsolNa, &out.NumUnsolNa
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.PacketsPerSlave != nil {
		in, out := &in.PacketsPerSlave, &out.PacketsPerSlave
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
	if in.PrimaryReselect != nil {
		in, out := &in.PrimaryReselect, &out.PrimaryReselect
		*out = new(BondPrimaryReselect)
		**out = **in
	}
	if in.ResendIgmp != nil {
		in, out := &in.ResendIgmp, &out.ResendIgmp
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TlbDynamicLb != nil {
		in, out := &in.TlbDynamicLb, &out.TlbDynamicLb
		*out = new(bool)
		**out = **in
	}
	if in.Updelay != nil {
		in, out := &in.Updelay, &out.Updelay
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.UseCarrier != nil {
		in, out := &in.UseCarrier, &out.UseCarrier
		*out = new(bool)
		**out = **in
	}
	if in.XmitHashPolicy != nil {
		in, out := &in.XmitHashPolicy, &out.XmitHashPolicy
		*out = new(BondXmitHashPolicy)
		**out = **in
	}
	if in.BalanceSlb != nil {
		in, out := &in.BalanceSlb, &out.BalanceSlb
		*out = new(bool)
		**out = **in
	}
	if in.ArpMissedMax != nil {
		in, out := &in.ArpMissedMax, &out.ArpMissedMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondOptions.
func (in *BondOptions) DeepCopy() *BondOptions {
	if in == nil {
		return nil
	}
	out := new(BondOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BondPortConfig) DeepCopyInto(out *BondPortConfig) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.QueueId != nil {
		in, out := &in.QueueId, &out.QueueId
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondPortConfig.
func (in *BondPortConfig) DeepCopy() *BondPortConfig {
	if in == nil {
		return nil
	}
	out := new(BondPortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeConfig) DeepCopyInto(out *BridgeConfig) {
	*out = *in
	if in.OvsBridgeConfig != nil {
		in, out := &in.OvsBridgeConfig, &out.OvsBridgeConfig
		*out = new(OvsBridgeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(BridgeOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]BridgePortConfig)
		if **in != nil {
			in, out := *in, *out
			*out = make([]BridgePortConfig, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeConfig.
func (in *BridgeConfig) DeepCopy() *BridgeConfig {
	if in == nil {
		return nil
	}
	out := new(BridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInterface) DeepCopyInto(out *BridgeInterface) {
	*out = *in
	if in.BridgeConfig != nil {
		in, out := &in.BridgeConfig, &out.BridgeConfig
		*out = new(BridgeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInterface.
func (in *BridgeInterface) DeepCopy() *BridgeInterface {
	if in == nil {
		return nil
	}
	out := new(BridgeInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeOptions) DeepCopyInto(out *BridgeOptions) {
	*out = *in
	if in.LinuxBridgeOptions != nil {
		in, out := &in.LinuxBridgeOptions, &out.LinuxBridgeOptions
		*out = new(LinuxBridgeOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.OvsBridgeOptions != nil {
		in, out := &in.OvsBridgeOptions, &out.OvsBridgeOptions
		*out = new(OvsBridgeOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeOptions.
func (in *BridgeOptions) DeepCopy() *BridgeOptions {
	if in == nil {
		return nil
	}
	out := new(BridgeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgePortConfig) DeepCopyInto(out *BridgePortConfig) {
	*out = *in
	in.BridgePortConfigMetaData.DeepCopyInto(&out.BridgePortConfigMetaData)
	if in.OvsBridgePortConfig != nil {
		in, out := &in.OvsBridgePortConfig, &out.OvsBridgePortConfig
		*out = new(OvsBridgePortConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LinuxBridgePortConfig != nil {
		in, out := &in.LinuxBridgePortConfig, &out.LinuxBridgePortConfig
		*out = new(LinuxBridgePortConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgePortConfig.
func (in *BridgePortConfig) DeepCopy() *BridgePortConfig {
	if in == nil {
		return nil
	}
	out := new(BridgePortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgePortConfigMetaData) DeepCopyInto(out *BridgePortConfigMetaData) {
	*out = *in
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(BridgePortVlanConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgePortConfigMetaData.
func (in *BridgePortConfigMetaData) DeepCopy() *BridgePortConfigMetaData {
	if in == nil {
		return nil
	}
	out := new(BridgePortConfigMetaData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgePortTrunkTag) DeepCopyInto(out *BridgePortTrunkTag) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(uint16)
		**out = **in
	}
	if in.IdRange != nil {
		in, out := &in.IdRange, &out.IdRange
		*out = new(BridgePortVlanRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgePortTrunkTag.
func (in *BridgePortTrunkTag) DeepCopy() *BridgePortTrunkTag {
	if in == nil {
		return nil
	}
	out := new(BridgePortTrunkTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgePortVlanConfig) DeepCopyInto(out *BridgePortVlanConfig) {
	*out = *in
	if in.EnableNative != nil {
		in, out := &in.EnableNative, &out.EnableNative
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(BridgePortVlanMode)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TrunkTags != nil {
		in, out := &in.TrunkTags, &out.TrunkTags
		*out = new([]BridgePortTrunkTag)
		if **in != nil {
			in, out := *in, *out
			*out = make([]BridgePortTrunkTag, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgePortVlanConfig.
func (in *BridgePortVlanConfig) DeepCopy() *BridgePortVlanConfig {
	if in == nil {
		return nil
	}
	out := new(BridgePortVlanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgePortVlanRange) DeepCopyInto(out *BridgePortVlanRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgePortVlanRange.
func (in *BridgePortVlanRange) DeepCopy() *BridgePortVlanRange {
	if in == nil {
		return nil
	}
	out := new(BridgePortVlanRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchConfig) DeepCopyInto(out *DispatchConfig) {
	*out = *in
	if in.PostActivation != nil {
		in, out := &in.PostActivation, &out.PostActivation
		*out = new(string)
		**out = **in
	}
	if in.PostDeactivation != nil {
		in, out := &in.PostDeactivation, &out.PostDeactivation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchConfig.
func (in *DispatchConfig) DeepCopy() *DispatchConfig {
	if in == nil {
		return nil
	}
	out := new(DispatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsClientState) DeepCopyInto(out *DnsClientState) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsClientState.
func (in *DnsClientState) DeepCopy() *DnsClientState {
	if in == nil {
		return nil
	}
	out := new(DnsClientState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsState) DeepCopyInto(out *DnsState) {
	*out = *in
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(DnsClientState)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(DnsClientState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsState.
func (in *DnsState) DeepCopy() *DnsState {
	if in == nil {
		return nil
	}
	out := new(DnsState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DummyInterface) DeepCopyInto(out *DummyInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DummyInterface.
func (in *DummyInterface) DeepCopy() *DummyInterface {
	if in == nil {
		return nil
	}
	out := new(DummyInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthernetConfig) DeepCopyInto(out *EthernetConfig) {
	*out = *in
	if in.SrIov != nil {
		in, out := &in.SrIov, &out.SrIov
		*out = new(SrIovConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoNeg != nil {
		in, out := &in.AutoNeg, &out.AutoNeg
		*out = new(bool)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Duplex != nil {
		in, out := &in.Duplex, &out.Duplex
		*out = new(EthernetDuplex)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthernetConfig.
func (in *EthernetConfig) DeepCopy() *EthernetConfig {
	if in == nil {
		return nil
	}
	out := new(EthernetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthernetInterface) DeepCopyInto(out *EthernetInterface) {
	*out = *in
	if in.Ethernet != nil {
		in, out := &in.Ethernet, &out.Ethernet
		*out = new(EthernetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Veth != nil {
		in, out := &in.Veth, &out.Veth
		*out = new(VethConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthernetInterface.
func (in *EthernetInterface) DeepCopy() *EthernetInterface {
	if in == nil {
		return nil
	}
	out := new(EthernetInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthtoolCoalesceConfig) DeepCopyInto(out *EthtoolCoalesceConfig) {
	*out = *in
	if in.AdaptiveRx != nil {
		in, out := &in.AdaptiveRx, &out.AdaptiveRx
		*out = new(bool)
		**out = **in
	}
	if in.AdaptiveTx != nil {
		in, out := &in.AdaptiveTx, &out.AdaptiveTx
		*out = new(bool)
		**out = **in
	}
	if in.PktRateHigh != nil {
		in, out := &in.PktRateHigh, &out.PktRateHigh
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.PktRateLow != nil {
		in, out := &in.PktRateLow, &out.PktRateLow
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxFrames != nil {
		in, out := &in.RxFrames, &out.RxFrames
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxFramesHigh != nil {
		in, out := &in.RxFramesHigh, &out.RxFramesHigh
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxFramesIrq != nil {
		in, out := &in.RxFramesIrq, &out.RxFramesIrq
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxFramesLow != nil {
		in, out := &in.RxFramesLow, &out.RxFramesLow
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxUsecs != nil {
		in, out := &in.RxUsecs, &out.RxUsecs
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxUsecsHigh != nil {
		in, out := &in.RxUsecsHigh, &out.RxUsecsHigh
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxUsecsIrq != nil {
		in, out := &in.RxUsecsIrq, &out.RxUsecsIrq
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxUsecsLow != nil {
		in, out := &in.RxUsecsLow, &out.RxUsecsLow
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.SampleInterval != nil {
		in, out := &in.SampleInterval, &out.SampleInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.StatsBlockUsecs != nil {
		in, out := &in.StatsBlockUsecs, &out.StatsBlockUsecs
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxFrames != nil {
		in, out := &in.TxFrames, &out.TxFrames
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxFramesHigh != nil {
		in, out := &in.TxFramesHigh, &out.TxFramesHigh
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxFramesIrq != nil {
		in, out := &in.TxFramesIrq, &out.TxFramesIrq
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxFramesLow != nil {
		in, out := &in.TxFramesLow, &out.TxFramesLow
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxUsecs != nil {
		in, out := &in.TxUsecs, &out.TxUsecs
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxUsecsHigh != nil {
		in, out := &in.TxUsecsHigh, &out.TxUsecsHigh
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxUsecsIrq != nil {
		in, out := &in.TxUsecsIrq, &out.TxUsecsIrq
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxUsecsLow != nil {
		in, out := &in.TxUsecsLow, &out.TxUsecsLow
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthtoolCoalesceConfig.
func (in *EthtoolCoalesceConfig) DeepCopy() *EthtoolCoalesceConfig {
	if in == nil {
		return nil
	}
	out := new(EthtoolCoalesceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthtoolConfig) DeepCopyInto(out *EthtoolConfig) {
	*out = *in
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(EthtoolPauseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Coalesce != nil {
		in, out := &in.Coalesce, &out.Coalesce
		*out = new(EthtoolCoalesceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ring != nil {
		in, out := &in.Ring, &out.Ring
		*out = new(EthtoolRingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthtoolConfig.
func (in *EthtoolConfig) DeepCopy() *EthtoolConfig {
	if in == nil {
		return nil
	}
	out := new(EthtoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthtoolFeatureConfig) DeepCopyInto(out *EthtoolFeatureConfig) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthtoolFeatureConfig.
func (in *EthtoolFeatureConfig) DeepCopy() *EthtoolFeatureConfig {
	if in == nil {
		return nil
	}
	out := new(EthtoolFeatureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthtoolPauseConfig) DeepCopyInto(out *EthtoolPauseConfig) {
	*out = *in
	if in.Rx != nil {
		in, out := &in.Rx, &out.Rx
		*out = new(bool)
		**out = **in
	}
	if in.Tx != nil {
		in, out := &in.Tx, &out.Tx
		*out = new(bool)
		**out = **in
	}
	if in.Autoneg != nil {
		in, out := &in.Autoneg, &out.Autoneg
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthtoolPauseConfig.
func (in *EthtoolPauseConfig) DeepCopy() *EthtoolPauseConfig {
	if in == nil {
		return nil
	}
	out := new(EthtoolPauseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthtoolRingConfig) DeepCopyInto(out *EthtoolRingConfig) {
	*out = *in
	if in.Rx != nil {
		in, out := &in.Rx, &out.Rx
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxMax != nil {
		in, out := &in.RxMax, &out.RxMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxJumbo != nil {
		in, out := &in.RxJumbo, &out.RxJumbo
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxJumboMax != nil {
		in, out := &in.RxJumboMax, &out.RxJumboMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxMini != nil {
		in, out := &in.RxMini, &out.RxMini
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RxMiniMax != nil {
		in, out := &in.RxMiniMax, &out.RxMiniMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Tx != nil {
		in, out := &in.Tx, &out.Tx
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TxMax != nil {
		in, out := &in.TxMax, &out.TxMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthtoolRingConfig.
func (in *EthtoolRingConfig) DeepCopy() *EthtoolRingConfig {
	if in == nil {
		return nil
	}
	out := new(EthtoolRingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostNameState) DeepCopyInto(out *HostNameState) {
	*out = *in
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostNameState.
func (in *HostNameState) DeepCopy() *HostNameState {
	if in == nil {
		return nil
	}
	out := new(HostNameState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ieee8021XConfig) DeepCopyInto(out *Ieee8021XConfig) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(string)
		**out = **in
	}
	if in.Eap != nil {
		in, out := &in.Eap, &out.Eap
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(string)
		**out = **in
	}
	if in.ClientCert != nil {
		in, out := &in.ClientCert, &out.ClientCert
		*out = new(string)
		**out = **in
	}
	if in.CaCert != nil {
		in, out := &in.CaCert, &out.CaCert
		*out = new(string)
		**out = **in
	}
	if in.PrivateKeyPassword != nil {
		in, out := &in.PrivateKeyPassword, &out.PrivateKeyPassword
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ieee8021XConfig.
func (in *Ieee8021XConfig) DeepCopy() *Ieee8021XConfig {
	if in == nil {
		return nil
	}
	out := new(Ieee8021XConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfiniBandConfig) DeepCopyInto(out *InfiniBandConfig) {
	*out = *in
	if in.BaseIface != nil {
		in, out := &in.BaseIface, &out.BaseIface
		*out = new(string)
		**out = **in
	}
	if in.Pkey != nil {
		in, out := &in.Pkey, &out.Pkey
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfiniBandConfig.
func (in *InfiniBandConfig) DeepCopy() *InfiniBandConfig {
	if in == nil {
		return nil
	}
	out := new(InfiniBandConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfiniBandInterface) DeepCopyInto(out *InfiniBandInterface) {
	*out = *in
	if in.Ib != nil {
		in, out := &in.Ib, &out.Ib
		*out = new(InfiniBandConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfiniBandInterface.
func (in *InfiniBandInterface) DeepCopy() *InfiniBandInterface {
	if in == nil {
		return nil
	}
	out := new(InfiniBandInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface) DeepCopyInto(out *Interface) {
	*out = *in
	in.BaseInterface.DeepCopyInto(&out.BaseInterface)
	if in.BridgeInterface != nil {
		in, out := &in.BridgeInterface, &out.BridgeInterface
		*out = new(BridgeInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.BondInterface != nil {
		in, out := &in.BondInterface, &out.BondInterface
		*out = new(BondInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.EthernetInterface != nil {
		in, out := &in.EthernetInterface, &out.EthernetInterface
		*out = new(EthernetInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.OvsInterface != nil {
		in, out := &in.OvsInterface, &out.OvsInterface
		*out = new(OvsInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.VlanInterface != nil {
		in, out := &in.VlanInterface, &out.VlanInterface
		*out = new(VlanInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.VxlanInterface != nil {
		in, out := &in.VxlanInterface, &out.VxlanInterface
		*out = new(VxlanInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.MacVlanInterface != nil {
		in, out := &in.MacVlanInterface, &out.MacVlanInterface
		*out = new(MacVlanInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.MacVtapInterface != nil {
		in, out := &in.MacVtapInterface, &out.MacVtapInterface
		*out = new(MacVtapInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.VrfInterface != nil {
		in, out := &in.VrfInterface, &out.VrfInterface
		*out = new(VrfInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.InfiniBandInterface != nil {
		in, out := &in.InfiniBandInterface, &out.InfiniBandInterface
		*out = new(InfiniBandInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.MacSecInterface != nil {
		in, out := &in.MacSecInterface, &out.MacSecInterface
		*out = new(MacSecInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.IpsecInterface != nil {
		in, out := &in.IpsecInterface, &out.IpsecInterface
		*out = new(IpsecInterface)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Interface) DeepCopy() *Interface {
	if in == nil {
		return nil
	}
	out := new(Interface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceIp) DeepCopyInto(out *InterfaceIp) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Dhcp != nil {
		in, out := &in.Dhcp, &out.Dhcp
		*out = new(bool)
		**out = **in
	}
	if in.Autoconf != nil {
		in, out := &in.Autoconf, &out.Autoconf
		*out = new(bool)
		**out = **in
	}
	if in.DhcpClientId != nil {
		in, out := &in.DhcpClientId, &out.DhcpClientId
		*out = new(Dhcpv4ClientId)
		**out = **in
	}
	if in.DhcpDuid != nil {
		in, out := &in.DhcpDuid, &out.DhcpDuid
		*out = new(Dhcpv6Duid)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new([]InterfaceIpAddr)
		if **in != nil {
			in, out := *in, *out
			*out = make([]InterfaceIpAddr, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.AutoDns != nil {
		in, out := &in.AutoDns, &out.AutoDns
		*out = new(bool)
		**out = **in
	}
	if in.AutoGateway != nil {
		in, out := &in.AutoGateway, &out.AutoGateway
		*out = new(bool)
		**out = **in
	}
	if in.AutoRoutes != nil {
		in, out := &in.AutoRoutes, &out.AutoRoutes
		*out = new(bool)
		**out = **in
	}
	if in.AutoTableId != nil {
		in, out := &in.AutoTableId, &out.AutoTableId
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.AutoRouteMetric != nil {
		in, out := &in.AutoRouteMetric, &out.AutoRouteMetric
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.AddrGenMode != nil {
		in, out := &in.AddrGenMode, &out.AddrGenMode
		*out = new(Ipv6AddrGenMode)
		**out = **in
	}
	if in.AllowExtraAddress != nil {
		in, out := &in.AllowExtraAddress, &out.AllowExtraAddress
		*out = new(bool)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
	if in.DhcpSendHostname != nil {
		in, out := &in.DhcpSendHostname, &out.DhcpSendHostname
		*out = new(bool)
		**out = **in
	}
	if in.DhcpCustomHostname != nil {
		in, out := &in.DhcpCustomHostname, &out.DhcpCustomHostname
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceIp.
func (in *InterfaceIp) DeepCopy() *InterfaceIp {
	if in == nil {
		return nil
	}
	out := new(InterfaceIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceIpAddr) DeepCopyInto(out *InterfaceIpAddr) {
	*out = *in
	if in.MptcpFlags != nil {
		in, out := &in.MptcpFlags, &out.MptcpFlags
		*out = new([]MptcpAddressFlag)
		if **in != nil {
			in, out := *in, *out
			*out = make([]MptcpAddressFlag, len(*in))
			copy(*out, *in)
		}
	}
	if in.ValidLeft != nil {
		in, out := &in.ValidLeft, &out.ValidLeft
		*out = new(string)
		**out = **in
	}
	if in.PreferredLeft != nil {
		in, out := &in.PreferredLeft, &out.PreferredLeft
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceIpAddr.
func (in *InterfaceIpAddr) DeepCopy() *InterfaceIpAddr {
	if in == nil {
		return nil
	}
	out := new(InterfaceIpAddr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpsecInterface) DeepCopyInto(out *IpsecInterface) {
	*out = *in
	if in.Libreswan != nil {
		in, out := &in.Libreswan, &out.Libreswan
		*out = new(LibreswanConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpsecInterface.
func (in *IpsecInterface) DeepCopy() *IpsecInterface {
	if in == nil {
		return nil
	}
	out := new(IpsecInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibreswanConfig) DeepCopyInto(out *LibreswanConfig) {
	*out = *in
	if in.Rightid != nil {
		in, out := &in.Rightid, &out.Rightid
		*out = new(string)
		**out = **in
	}
	if in.Rightrsasigkey != nil {
		in, out := &in.Rightrsasigkey, &out.Rightrsasigkey
		*out = new(string)
		**out = **in
	}
	if in.Left != nil {
		in, out := &in.Left, &out.Left
		*out = new(string)
		**out = **in
	}
	if in.Leftid != nil {
		in, out := &in.Leftid, &out.Leftid
		*out = new(string)
		**out = **in
	}
	if in.Leftrsasigkey != nil {
		in, out := &in.Leftrsasigkey, &out.Leftrsasigkey
		*out = new(string)
		**out = **in
	}
	if in.Leftcert != nil {
		in, out := &in.Leftcert, &out.Leftcert
		*out = new(string)
		**out = **in
	}
	if in.Ikev2 != nil {
		in, out := &in.Ikev2, &out.Ikev2
		*out = new(string)
		**out = **in
	}
	if in.Psk != nil {
		in, out := &in.Psk, &out.Psk
		*out = new(string)
		**out = **in
	}
	if in.Ikelifetime != nil {
		in, out := &in.Ikelifetime, &out.Ikelifetime
		*out = new(string)
		**out = **in
	}
	if in.Salifetime != nil {
		in, out := &in.Salifetime, &out.Salifetime
		*out = new(string)
		**out = **in
	}
	if in.Ike != nil {
		in, out := &in.Ike, &out.Ike
		*out = new(string)
		**out = **in
	}
	if in.Esp != nil {
		in, out := &in.Esp, &out.Esp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibreswanConfig.
func (in *LibreswanConfig) DeepCopy() *LibreswanConfig {
	if in == nil {
		return nil
	}
	out := new(LibreswanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxBridgeConfig) DeepCopyInto(out *LinuxBridgeConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(LinuxBridgeOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new([]LinuxBridgePortConfig)
		if **in != nil {
			in, out := *in, *out
			*out = make([]LinuxBridgePortConfig, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxBridgeConfig.
func (in *LinuxBridgeConfig) DeepCopy() *LinuxBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxBridgeOptions) DeepCopyInto(out *LinuxBridgeOptions) {
	*out = *in
	if in.GcTimer != nil {
		in, out := &in.GcTimer, &out.GcTimer
		*out = new(uint64)
		**out = **in
	}
	if in.GroupAddr != nil {
		in, out := &in.GroupAddr, &out.GroupAddr
		*out = new(string)
		**out = **in
	}
	if in.GroupForwardMask != nil {
		in, out := &in.GroupForwardMask, &out.GroupForwardMask
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.GroupFwdMask != nil {
		in, out := &in.GroupFwdMask, &out.GroupFwdMask
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.HashMax != nil {
		in, out := &in.HashMax, &out.HashMax
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.HelloTimer != nil {
		in, out := &in.HelloTimer, &out.HelloTimer
		*out = new(uint64)
		**out = **in
	}
	if in.MacAgeingTime != nil {
		in, out := &in.MacAgeingTime, &out.MacAgeingTime
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastLastMemberCount != nil {
		in, out := &in.MulticastLastMemberCount, &out.MulticastLastMemberCount
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastLastMemberInterval != nil {
		in, out := &in.MulticastLastMemberInterval, &out.MulticastLastMemberInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastMembershipInterval != nil {
		in, out := &in.MulticastMembershipInterval, &out.MulticastMembershipInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastQuerier != nil {
		in, out := &in.MulticastQuerier, &out.MulticastQuerier
		*out = new(bool)
		**out = **in
	}
	if in.MulticastQuerierInterval != nil {
		in, out := &in.MulticastQuerierInterval, &out.MulticastQuerierInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastQueryInterval != nil {
		in, out := &in.MulticastQueryInterval, &out.MulticastQueryInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastQueryResponseInterval != nil {
		in, out := &in.MulticastQueryResponseInterval, &out.MulticastQueryResponseInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastQueryUseIfaddr != nil {
		in, out := &in.MulticastQueryUseIfaddr, &out.MulticastQueryUseIfaddr
		*out = new(bool)
		**out = **in
	}
	if in.MulticastRouter != nil {
		in, out := &in.MulticastRouter, &out.MulticastRouter
		*out = new(LinuxBridgeMulticastRouterType)
		**out = **in
	}
	if in.MulticastSnooping != nil {
		in, out := &in.MulticastSnooping, &out.MulticastSnooping
		*out = new(bool)
		**out = **in
	}
	if in.MulticastStartupQueryCount != nil {
		in, out := &in.MulticastStartupQueryCount, &out.MulticastStartupQueryCount
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MulticastStartupQueryInterval != nil {
		in, out := &in.MulticastStartupQueryInterval, &out.MulticastStartupQueryInterval
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Stp != nil {
		in, out := &in.Stp, &out.Stp
		*out = new(LinuxBridgeStpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.VlanProtocol != nil {
		in, out := &in.VlanProtocol, &out.VlanProtocol
		*out = new(VlanProtocol)
		**out = **in
	}
	if in.VlanDefaultPvid != nil {
		in, out := &in.VlanDefaultPvid, &out.VlanDefaultPvid
		*out = new(uint16)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxBridgeOptions.
func (in *LinuxBridgeOptions) DeepCopy() *LinuxBridgeOptions {
	if in == nil {
		return nil
	}
	out := new(LinuxBridgeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxBridgePortConfig) DeepCopyInto(out *LinuxBridgePortConfig) {
	*out = *in
	if in.StpHairpinMode != nil {
		in, out := &in.StpHairpinMode, &out.StpHairpinMode
		*out = new(bool)
		**out = **in
	}
	if in.StpPathCost != nil {
		in, out := &in.StpPathCost, &out.StpPathCost
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.StpPriority != nil {
		in, out := &in.StpPriority, &out.StpPriority
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxBridgePortConfig.
func (in *LinuxBridgePortConfig) DeepCopy() *LinuxBridgePortConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxBridgePortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxBridgeStpOptions) DeepCopyInto(out *LinuxBridgeStpOptions) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ForwardDelay != nil {
		in, out := &in.ForwardDelay, &out.ForwardDelay
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.HelloTime != nil {
		in, out := &in.HelloTime, &out.HelloTime
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxBridgeStpOptions.
func (in *LinuxBridgeStpOptions) DeepCopy() *LinuxBridgeStpOptions {
	if in == nil {
		return nil
	}
	out := new(LinuxBridgeStpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpChassisId) DeepCopyInto(out *LldpChassisId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpChassisId.
func (in *LldpChassisId) DeepCopy() *LldpChassisId {
	if in == nil {
		return nil
	}
	out := new(LldpChassisId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpConfig) DeepCopyInto(out *LldpConfig) {
	*out = *in
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([][]LldpNeighborTlv, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]LldpNeighborTlv, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpConfig.
func (in *LldpConfig) DeepCopy() *LldpConfig {
	if in == nil {
		return nil
	}
	out := new(LldpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpMacPhyConf) DeepCopyInto(out *LldpMacPhyConf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpMacPhyConf.
func (in *LldpMacPhyConf) DeepCopy() *LldpMacPhyConf {
	if in == nil {
		return nil
	}
	out := new(LldpMacPhyConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpMaxFrameSize) DeepCopyInto(out *LldpMaxFrameSize) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpMaxFrameSize.
func (in *LldpMaxFrameSize) DeepCopy() *LldpMaxFrameSize {
	if in == nil {
		return nil
	}
	out := new(LldpMaxFrameSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpMgmtAddr) DeepCopyInto(out *LldpMgmtAddr) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpMgmtAddr.
func (in *LldpMgmtAddr) DeepCopy() *LldpMgmtAddr {
	if in == nil {
		return nil
	}
	out := new(LldpMgmtAddr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpMgmtAddrs) DeepCopyInto(out *LldpMgmtAddrs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpMgmtAddrs.
func (in *LldpMgmtAddrs) DeepCopy() *LldpMgmtAddrs {
	if in == nil {
		return nil
	}
	out := new(LldpMgmtAddrs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpPortId) DeepCopyInto(out *LldpPortId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpPortId.
func (in *LldpPortId) DeepCopy() *LldpPortId {
	if in == nil {
		return nil
	}
	out := new(LldpPortId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpPpvids) DeepCopyInto(out *LldpPpvids) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpPpvids.
func (in *LldpPpvids) DeepCopy() *LldpPpvids {
	if in == nil {
		return nil
	}
	out := new(LldpPpvids)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpSystemCapabilities) DeepCopyInto(out *LldpSystemCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpSystemCapabilities.
func (in *LldpSystemCapabilities) DeepCopy() *LldpSystemCapabilities {
	if in == nil {
		return nil
	}
	out := new(LldpSystemCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpSystemDescription) DeepCopyInto(out *LldpSystemDescription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpSystemDescription.
func (in *LldpSystemDescription) DeepCopy() *LldpSystemDescription {
	if in == nil {
		return nil
	}
	out := new(LldpSystemDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpSystemName) DeepCopyInto(out *LldpSystemName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpSystemName.
func (in *LldpSystemName) DeepCopy() *LldpSystemName {
	if in == nil {
		return nil
	}
	out := new(LldpSystemName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpVlan) DeepCopyInto(out *LldpVlan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpVlan.
func (in *LldpVlan) DeepCopy() *LldpVlan {
	if in == nil {
		return nil
	}
	out := new(LldpVlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LldpVlans) DeepCopyInto(out *LldpVlans) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LldpVlans.
func (in *LldpVlans) DeepCopy() *LldpVlans {
	if in == nil {
		return nil
	}
	out := new(LldpVlans)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopbackInterface) DeepCopyInto(out *LoopbackInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopbackInterface.
func (in *LoopbackInterface) DeepCopy() *LoopbackInterface {
	if in == nil {
		return nil
	}
	out := new(LoopbackInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacSecConfig) DeepCopyInto(out *MacSecConfig) {
	*out = *in
	if in.MkaCak != nil {
		in, out := &in.MkaCak, &out.MkaCak
		*out = new(string)
		**out = **in
	}
	if in.MkaCkn != nil {
		in, out := &in.MkaCkn, &out.MkaCkn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacSecConfig.
func (in *MacSecConfig) DeepCopy() *MacSecConfig {
	if in == nil {
		return nil
	}
	out := new(MacSecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacSecInterface) DeepCopyInto(out *MacSecInterface) {
	*out = *in
	if in.Macsec != nil {
		in, out := &in.Macsec, &out.Macsec
		*out = new(MacSecConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacSecInterface.
func (in *MacSecInterface) DeepCopy() *MacSecInterface {
	if in == nil {
		return nil
	}
	out := new(MacSecInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacVlanConfig) DeepCopyInto(out *MacVlanConfig) {
	*out = *in
	if in.AcceptAllMac != nil {
		in, out := &in.AcceptAllMac, &out.AcceptAllMac
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacVlanConfig.
func (in *MacVlanConfig) DeepCopy() *MacVlanConfig {
	if in == nil {
		return nil
	}
	out := new(MacVlanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacVlanInterface) DeepCopyInto(out *MacVlanInterface) {
	*out = *in
	if in.MacVlan != nil {
		in, out := &in.MacVlan, &out.MacVlan
		*out = new(MacVlanConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacVlanInterface.
func (in *MacVlanInterface) DeepCopy() *MacVlanInterface {
	if in == nil {
		return nil
	}
	out := new(MacVlanInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacVtapConfig) DeepCopyInto(out *MacVtapConfig) {
	*out = *in
	if in.AcceptAllMac != nil {
		in, out := &in.AcceptAllMac, &out.AcceptAllMac
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacVtapConfig.
func (in *MacVtapConfig) DeepCopy() *MacVtapConfig {
	if in == nil {
		return nil
	}
	out := new(MacVtapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacVtapInterface) DeepCopyInto(out *MacVtapInterface) {
	*out = *in
	if in.MacVtap != nil {
		in, out := &in.MacVtap, &out.MacVtap
		*out = new(MacVtapConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacVtapInterface.
func (in *MacVtapInterface) DeepCopy() *MacVtapInterface {
	if in == nil {
		return nil
	}
	out := new(MacVtapInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MptcpConfig) DeepCopyInto(out *MptcpConfig) {
	*out = *in
	if in.AddressFlags != nil {
		in, out := &in.AddressFlags, &out.AddressFlags
		*out = new([]MptcpAddressFlag)
		if **in != nil {
			in, out := *in, *out
			*out = make([]MptcpAddressFlag, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MptcpConfig.
func (in *MptcpConfig) DeepCopy() *MptcpConfig {
	if in == nil {
		return nil
	}
	out := new(MptcpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkState) DeepCopyInto(out *NetworkState) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(HostNameState)
		(*in).DeepCopyInto(*out)
	}
	if in.Dns != nil {
		in, out := &in.Dns, &out.Dns
		*out = new(DnsState)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(RouteRules)
		(*in).DeepCopyInto(*out)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = new(Routes)
		(*in).DeepCopyInto(*out)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]Interface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ovsdb != nil {
		in, out := &in.Ovsdb, &out.Ovsdb
		*out = new(OvsDbGlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ovn != nil {
		in, out := &in.Ovn, &out.Ovn
		*out = new(OvnConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkState.
func (in *NetworkState) DeepCopy() *NetworkState {
	if in == nil {
		return nil
	}
	out := new(NetworkState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnBridgeMapping) DeepCopyInto(out *OvnBridgeMapping) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(OvnBridgeMappingState)
		**out = **in
	}
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnBridgeMapping.
func (in *OvnBridgeMapping) DeepCopy() *OvnBridgeMapping {
	if in == nil {
		return nil
	}
	out := new(OvnBridgeMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnConfiguration) DeepCopyInto(out *OvnConfiguration) {
	*out = *in
	if in.BridgeMappings != nil {
		in, out := &in.BridgeMappings, &out.BridgeMappings
		*out = new([]OvnBridgeMapping)
		if **in != nil {
			in, out := *in, *out
			*out = make([]OvnBridgeMapping, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnConfiguration.
func (in *OvnConfiguration) DeepCopy() *OvnConfiguration {
	if in == nil {
		return nil
	}
	out := new(OvnConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgeBondConfig) DeepCopyInto(out *OvsBridgeBondConfig) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(OvsBridgeBondMode)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]OvsBridgeBondPortConfig)
		if **in != nil {
			in, out := *in, *out
			*out = make([]OvsBridgeBondPortConfig, len(*in))
			copy(*out, *in)
		}
	}
	if in.BondDowndelay != nil {
		in, out := &in.BondDowndelay, &out.BondDowndelay
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.BondUpdelay != nil {
		in, out := &in.BondUpdelay, &out.BondUpdelay
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Ovsdb != nil {
		in, out := &in.Ovsdb, &out.Ovsdb
		*out = new(OvsDbIfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgeBondConfig.
func (in *OvsBridgeBondConfig) DeepCopy() *OvsBridgeBondConfig {
	if in == nil {
		return nil
	}
	out := new(OvsBridgeBondConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgeBondPortConfig) DeepCopyInto(out *OvsBridgeBondPortConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgeBondPortConfig.
func (in *OvsBridgeBondPortConfig) DeepCopy() *OvsBridgeBondPortConfig {
	if in == nil {
		return nil
	}
	out := new(OvsBridgeBondPortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgeConfig) DeepCopyInto(out *OvsBridgeConfig) {
	*out = *in
	if in.AllowExtraPatchPorts != nil {
		in, out := &in.AllowExtraPatchPorts, &out.AllowExtraPatchPorts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgeConfig.
func (in *OvsBridgeConfig) DeepCopy() *OvsBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(OvsBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgeOptions) DeepCopyInto(out *OvsBridgeOptions) {
	*out = *in
	if in.Stp != nil {
		in, out := &in.Stp, &out.Stp
		*out = new(OvsBridgeStpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Rstp != nil {
		in, out := &in.Rstp, &out.Rstp
		*out = new(bool)
		**out = **in
	}
	if in.McastSnoopingEnable != nil {
		in, out := &in.McastSnoopingEnable, &out.McastSnoopingEnable
		*out = new(bool)
		**out = **in
	}
	if in.FailMode != nil {
		in, out := &in.FailMode, &out.FailMode
		*out = new(string)
		**out = **in
	}
	if in.Datapath != nil {
		in, out := &in.Datapath, &out.Datapath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgeOptions.
func (in *OvsBridgeOptions) DeepCopy() *OvsBridgeOptions {
	if in == nil {
		return nil
	}
	out := new(OvsBridgeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgePortConfig) DeepCopyInto(out *OvsBridgePortConfig) {
	*out = *in
	if in.Bond != nil {
		in, out := &in.Bond, &out.Bond
		*out = new(OvsBridgeBondConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgePortConfig.
func (in *OvsBridgePortConfig) DeepCopy() *OvsBridgePortConfig {
	if in == nil {
		return nil
	}
	out := new(OvsBridgePortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsBridgeStpOptions) DeepCopyInto(out *OvsBridgeStpOptions) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsBridgeStpOptions.
func (in *OvsBridgeStpOptions) DeepCopy() *OvsBridgeStpOptions {
	if in == nil {
		return nil
	}
	out := new(OvsBridgeStpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDbGlobalConfig) DeepCopyInto(out *OvsDbGlobalConfig) {
	*out = *in
	if in.ExternalIds != nil {
		in, out := &in.ExternalIds, &out.ExternalIds
		*out = new(map[string]*string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*string, len(*in))
			for key, val := range *in {
				var outVal *string
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(string)
					**out = **in
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.OtherConfig != nil {
		in, out := &in.OtherConfig, &out.OtherConfig
		*out = new(map[string]*string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*string, len(*in))
			for key, val := range *in {
				var outVal *string
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(string)
					**out = **in
				}
				(*out)[key] = outVal
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDbGlobalConfig.
func (in *OvsDbGlobalConfig) DeepCopy() *OvsDbGlobalConfig {
	if in == nil {
		return nil
	}
	out := new(OvsDbGlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDbIfaceConfig) DeepCopyInto(out *OvsDbIfaceConfig) {
	*out = *in
	if in.ExternalIds != nil {
		in, out := &in.ExternalIds, &out.ExternalIds
		*out = new(map[string]*string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*string, len(*in))
			for key, val := range *in {
				var outVal *string
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(string)
					**out = **in
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.OtherConfig != nil {
		in, out := &in.OtherConfig, &out.OtherConfig
		*out = new(map[string]*string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*string, len(*in))
			for key, val := range *in {
				var outVal *string
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(string)
					**out = **in
				}
				(*out)[key] = outVal
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDbIfaceConfig.
func (in *OvsDbIfaceConfig) DeepCopy() *OvsDbIfaceConfig {
	if in == nil {
		return nil
	}
	out := new(OvsDbIfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkConfig) DeepCopyInto(out *OvsDpdkConfig) {
	*out = *in
	if in.RxQueue != nil {
		in, out := &in.RxQueue, &out.RxQueue
		*out = new(uint32)
		**out = **in
	}
	if in.NRxqDesc != nil {
		in, out := &in.NRxqDesc, &out.NRxqDesc
		*out = new(uint32)
		**out = **in
	}
	if in.NTxqDesc != nil {
		in, out := &in.NTxqDesc, &out.NTxqDesc
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkConfig.
func (in *OvsDpdkConfig) DeepCopy() *OvsDpdkConfig {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsInterface) DeepCopyInto(out *OvsInterface) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(OvsPatchConfig)
		**out = **in
	}
	if in.Dpdk != nil {
		in, out := &in.Dpdk, &out.Dpdk
		*out = new(OvsDpdkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsInterface.
func (in *OvsInterface) DeepCopy() *OvsInterface {
	if in == nil {
		return nil
	}
	out := new(OvsInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsPatchConfig) DeepCopyInto(out *OvsPatchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsPatchConfig.
func (in *OvsPatchConfig) DeepCopy() *OvsPatchConfig {
	if in == nil {
		return nil
	}
	out := new(OvsPatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteEntry) DeepCopyInto(out *RouteEntry) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(RouteState)
		**out = **in
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
	if in.NextHopIface != nil {
		in, out := &in.NextHopIface, &out.NextHopIface
		*out = new(string)
		**out = **in
	}
	if in.NextHopAddr != nil {
		in, out := &in.NextHopAddr, &out.NextHopAddr
		*out = new(string)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TableId != nil {
		in, out := &in.TableId, &out.TableId
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.RouteType != nil {
		in, out := &in.RouteType, &out.RouteType
		*out = new(RouteType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteEntry.
func (in *RouteEntry) DeepCopy() *RouteEntry {
	if in == nil {
		return nil
	}
	out := new(RouteEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRuleEntry) DeepCopyInto(out *RouteRuleEntry) {
	*out = *in
	if in.Family != nil {
		in, out := &in.Family, &out.Family
		*out = new(AddressFamily)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(RouteRuleState)
		**out = **in
	}
	if in.IpFrom != nil {
		in, out := &in.IpFrom, &out.IpFrom
		*out = new(string)
		**out = **in
	}
	if in.IpTo != nil {
		in, out := &in.IpTo, &out.IpTo
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.TableId != nil {
		in, out := &in.TableId, &out.TableId
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Fwmark != nil {
		in, out := &in.Fwmark, &out.Fwmark
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Fwmask != nil {
		in, out := &in.Fwmask, &out.Fwmask
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(RouteRuleAction)
		**out = **in
	}
	if in.Iif != nil {
		in, out := &in.Iif, &out.Iif
		*out = new(string)
		**out = **in
	}
	if in.SuppressPrefixLength != nil {
		in, out := &in.SuppressPrefixLength, &out.SuppressPrefixLength
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRuleEntry.
func (in *RouteRuleEntry) DeepCopy() *RouteRuleEntry {
	if in == nil {
		return nil
	}
	out := new(RouteRuleEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRules) DeepCopyInto(out *RouteRules) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new([]RouteRuleEntry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RouteRuleEntry, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRules.
func (in *RouteRules) DeepCopy() *RouteRules {
	if in == nil {
		return nil
	}
	out := new(RouteRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Routes) DeepCopyInto(out *Routes) {
	*out = *in
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new([]RouteEntry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RouteEntry, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new([]RouteEntry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RouteEntry, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Routes.
func (in *Routes) DeepCopy() *Routes {
	if in == nil {
		return nil
	}
	out := new(Routes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrIovConfig) DeepCopyInto(out *SrIovConfig) {
	*out = *in
	if in.TotalVfs != nil {
		in, out := &in.TotalVfs, &out.TotalVfs
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Vfs != nil {
		in, out := &in.Vfs, &out.Vfs
		*out = new([]SrIovVfConfig)
		if **in != nil {
			in, out := *in, *out
			*out = make([]SrIovVfConfig, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrIovConfig.
func (in *SrIovConfig) DeepCopy() *SrIovConfig {
	if in == nil {
		return nil
	}
	out := new(SrIovConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrIovVfConfig) DeepCopyInto(out *SrIovVfConfig) {
	*out = *in
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(string)
		**out = **in
	}
	if in.SpoofCheck != nil {
		in, out := &in.SpoofCheck, &out.SpoofCheck
		*out = new(bool)
		**out = **in
	}
	if in.Trust != nil {
		in, out := &in.Trust, &out.Trust
		*out = new(bool)
		**out = **in
	}
	if in.MinTxRate != nil {
		in, out := &in.MinTxRate, &out.MinTxRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxTxRate != nil {
		in, out := &in.MaxTxRate, &out.MaxTxRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.VlanId != nil {
		in, out := &in.VlanId, &out.VlanId
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Qos != nil {
		in, out := &in.Qos, &out.Qos
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrIovVfConfig.
func (in *SrIovVfConfig) DeepCopy() *SrIovVfConfig {
	if in == nil {
		return nil
	}
	out := new(SrIovVfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnknownInterface) DeepCopyInto(out *UnknownInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnknownInterface.
func (in *UnknownInterface) DeepCopy() *UnknownInterface {
	if in == nil {
		return nil
	}
	out := new(UnknownInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VethConfig) DeepCopyInto(out *VethConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VethConfig.
func (in *VethConfig) DeepCopy() *VethConfig {
	if in == nil {
		return nil
	}
	out := new(VethConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanConfig) DeepCopyInto(out *VlanConfig) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(VlanProtocol)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanConfig.
func (in *VlanConfig) DeepCopy() *VlanConfig {
	if in == nil {
		return nil
	}
	out := new(VlanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanInterface) DeepCopyInto(out *VlanInterface) {
	*out = *in
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(VlanConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanInterface.
func (in *VlanInterface) DeepCopy() *VlanInterface {
	if in == nil {
		return nil
	}
	out := new(VlanInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfConfig) DeepCopyInto(out *VrfConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfConfig.
func (in *VrfConfig) DeepCopy() *VrfConfig {
	if in == nil {
		return nil
	}
	out := new(VrfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfInterface) DeepCopyInto(out *VrfInterface) {
	*out = *in
	if in.Vrf != nil {
		in, out := &in.Vrf, &out.Vrf
		*out = new(VrfConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfInterface.
func (in *VrfInterface) DeepCopy() *VrfInterface {
	if in == nil {
		return nil
	}
	out := new(VrfInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VxlanConfig) DeepCopyInto(out *VxlanConfig) {
	*out = *in
	if in.Learning != nil {
		in, out := &in.Learning, &out.Learning
		*out = new(bool)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(string)
		**out = **in
	}
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(string)
		**out = **in
	}
	if in.DstPort != nil {
		in, out := &in.DstPort, &out.DstPort
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VxlanConfig.
func (in *VxlanConfig) DeepCopy() *VxlanConfig {
	if in == nil {
		return nil
	}
	out := new(VxlanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VxlanInterface) DeepCopyInto(out *VxlanInterface) {
	*out = *in
	if in.Vxlan != nil {
		in, out := &in.Vxlan, &out.Vxlan
		*out = new(VxlanConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VxlanInterface.
func (in *VxlanInterface) DeepCopy() *VxlanInterface {
	if in == nil {
		return nil
	}
	out := new(VxlanInterface)
	in.DeepCopyInto(out)
	return out
}
