FROM registry.fedoraproject.org/fedora:rawhide

RUN echo "2023-11-06" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
        systemd make go rust cargo NetworkManager NetworkManager-ovs \
        NetworkManager-config-server openvswitch systemd-udev \
        python3-devel python3-pyyaml python3-setuptools dnsmasq git \
        iproute rpm-build python3-pytest python3-virtualenv python3-tox \
        tcpreplay wpa_supplicant hostapd libndp procps-ng dpdk nispor \
        patchelf rust-packaging python3-gobject-base NetworkManager-libreswan \
        libreswan && dnf clean all

COPY network_manager_enable_trace.conf \
     /etc/NetworkManager/conf.d/97-trace-logging.conf
COPY network_manager_keyfile.conf \
     /etc/NetworkManager/conf.d/96-keyfile.conf

RUN sed -i -e 's/^#RateLimitInterval=.*/RateLimitInterval=0/' \
    -e 's/^#RateLimitBurst=.*/RateLimitBurst=0/' \
    /etc/systemd/journald.conf

RUN echo net.ipv6.conf.all.disable_ipv6=0 > \
        /etc/sysctl.d/00-enable-ipv6.conf && \
    echo kernel.core_pattern=/exported-artifacts/core.%h.%e.%t > \
    /etc/sysctl.d/01-export-kernel-cores.conf

RUN systemctl enable systemd-udevd NetworkManager openvswitch ipsec

CMD ["/usr/sbin/init"]
