FROM registry.fedoraproject.org/fedora:rawhide

RUN echo "2024-04-09" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
        systemd make go rust cargo NetworkManager NetworkManager-ovs \
        openvswitch systemd-udev python3-devel python3-pyyaml \
        python3-setuptools dnsmasq git iproute rpm-build python3-pytest \
        python3-virtualenv python3-tox tcpreplay wpa_supplicant hostapd \
        libndp procps-ng dpdk rust-packaging \
        NetworkManager-libreswan libreswan \
        && dnf clean all

COPY network_manager_enable_trace.conf \
     /etc/NetworkManager/conf.d/97-trace-logging.conf
COPY network_manager_keyfile.conf \
     /etc/NetworkManager/conf.d/96-keyfile.conf

# Fedora container has no /etc/systemd/journald.conf file in systemd rpm
RUN  echo -e '[Journal]\nRateLimitInterval=0\nRateLimitBurst=0' > \
    /etc/systemd/journald.conf

RUN echo net.ipv6.conf.all.disable_ipv6=0 > \
        /etc/sysctl.d/00-enable-ipv6.conf && \
    echo kernel.core_pattern=/exported-artifacts/core.%h.%e.%t > \
    /etc/sysctl.d/01-export-kernel-cores.conf

RUN systemctl enable systemd-udevd NetworkManager openvswitch ipsec

CMD ["/usr/sbin/init"]
