FROM docker.io/library/centos:8

RUN dnf -y install dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled PowerTools && \
    dnf copr enable nmstate/ovs-el8 -y && \
    dnf copr enable networkmanager/NetworkManager-1.22 -y && \
    dnf -y install --setopt=install_weak_deps=False \
                   NetworkManager \
                   NetworkManager-ovs \
                   NetworkManager-team \
                   NetworkManager-config-server \
                   openvswitch2.11 \
                   systemd-udev \
                   python3-devel \
                   python3-gobject-base \
                   python3-jsonschema \
                   python3-pyyaml \
                   python3-setuptools \
                   python36 \
                   dnsmasq \
                   git \
                   iproute \
                   rpm-build \
                   python3-pytest \
                   python3-pytest-cov \
                   python3-virtualenv \
                   python3-tox \
                   python3-coveralls \
                   python3-requests \
                   python3-docopt \
                   && \
    alternatives --set python /usr/bin/python3 && \
    ln -s /usr/bin/pytest-3 /usr/bin/pytest && \
    dnf clean all && \
    systemctl enable openvswitch && \
    sed -i -e 's/^#RateLimitInterval=.*/RateLimitInterval=0/' \
    -e 's/^#RateLimitBurst=.*/RateLimitBurst=0/' \
    /etc/systemd/journald.conf

RUN rpm --verifydb

COPY network_manager_enable_trace.conf \
     /etc/NetworkManager/conf.d/97-trace-logging.conf

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
