FROM nmstate/centos_7_base

RUN yum -y install yum-utils && \
    yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/nmstate/nmstate-git-el7/repo/epel-7/nmstate-nmstate-git-el7-epel-7.repo && \
    yum -y install nmstate && \
    yum clean all

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
