FROM quay.io/centos/centos:stream10-development

RUN echo "2025-02-27" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
       systemd git make rust-toolset rpm-build python3 python3-devel && \
    dnf clean all
