FROM quay.io/centos/centos:stream9

RUN echo "2023-05-04" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
       systemd git make rust-toolset rpm-build python3 python3-devel && \
    dnf clean all
