FROM quay.io/centos/centos:stream8

RUN echo "2021-11-29" > /build_time

RUN sed -i -e 's/^#RateLimitInterval=.*/RateLimitInterval=0/' \
    -e 's/^#RateLimitBurst=.*/RateLimitBurst=0/' \
    /etc/systemd/journald.conf

RUN dnf update -y && \
    dnf -y install dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled powertools && \
    dnf copr enable nmstate/ovs-el8 -y && \
    dnf copr enable nmstate/nispor -y && \
    dnf -y install --setopt=install_weak_deps=False \
                   make \
                   rust-toolset \
                   NetworkManager \
                   NetworkManager-ovs \
                   NetworkManager-team \
                   NetworkManager-config-server \
                   openvswitch2.11 \
                   python3-openvswitch2.11 \
                   systemd-udev \
                   python3-devel \
                   python3-gobject-base \
                   python3-jsonschema \
                   python3-pyyaml \
                   python3-setuptools \
                   python36 \
                   dnsmasq \
                   git \
                   iproute \
                   rpm-build \
                   python3-pytest \
                   python3-pytest-cov \
                   python3-virtualenv \
                   python3-tox \
                   python3-coveralls \
                   python3-requests \
                   python3-docopt \
                   python3-nispor \
                   python3-varlink \
                   libvarlink-util \
                   tcpreplay \
                   wpa_supplicant \
                   hostapd \
                   libndp \
                   procps-ng \
                   && \
    alternatives --set python /usr/bin/python3 && \
    ln -s /usr/bin/pytest-3 /usr/bin/pytest && \
    dnf clean all && \
    systemctl enable openvswitch

COPY network_manager_enable_trace.conf \
     /etc/NetworkManager/conf.d/97-trace-logging.conf

RUN systemctl enable dbus systemd-udevd NetworkManager

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
