FROM quay.io/centos/centos:stream8

RUN echo "2022-03-07" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
       git make rust-toolset rpm-build python3 python3-devel && \
    dnf clean all
