name: Python

on:
  pull_request:
   types: [opened, synchronize, reopened]
  push:
    branches:
      - base

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_type: "c8s-nm_1_36-format"
          - job_type: "c8s-nm_1_36-lint"
          - job_type: "c8s-nm_1_36-unit_py36"
          - job_type: "c8s-nm_1_36-integ_tier1"
          - job_type: "c8s-nm_1_36-integ_tier2"
          - job_type: "c8s-nm_1_36-integ_slow"
          - job_type: "c8s-nm_1_36-integ_rust"
          - job_type: "ovs2_11-nm_1_36-integ_tier1"

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git gnupg2 openssh-client xz-utils podman

      - name: Enable openvswitch kernel module
        run: sudo modprobe openvswitch

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: .github/workflows/run_test.sh ${{ matrix.job_type }}

      - name: Set artifacts permissions
        if: ${{ failure() }}
        run: sudo chmod 777 test_artifacts/*

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: nmstate-test-artifact-${{ matrix.job_type }}
          path: test_artifacts/
          retention-days: 5
