name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      run: rustup update

    - name: Build release binrary
      run: cd rust && cargo build --release

    - uses: actions/upload-artifact@v4
      with:
        name: nmstatectl-linux-x64
        path: rust/target/release/nmstatectl
        retention-days: 30

  macos-x64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      run: rustup update && rustup target add x86_64-apple-darwin

    - name: Build release
      run: |
        cd rust && cargo build --release --target=x86_64-apple-darwin \
            --no-default-features --features gen_conf

    - uses: actions/upload-artifact@v4
      with:
        name: nmstatectl-macos-x64
        path: rust/target/x86_64-apple-darwin/release/nmstatectl
        retention-days: 30

  macos-aarch64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      run: rustup update && rustup target add aarch64-apple-darwin

    - name: Build release
      run: |
        cd rust && cargo build --release --target=aarch64-apple-darwin \
            --no-default-features --features gen_conf

    - uses: actions/upload-artifact@v4
      with:
        name: nmstatectl-macos-aarch64
        path: rust/target/aarch64-apple-darwin/release/nmstatectl
        retention-days: 30
